# https://render.com/docs/yaml-spec
services:
  - type: web
    region: frankfurt
    name: the-real-deal
    env: node
    buildCommand: NODE_ENV=development npm ci && npm run build
    startCommand: NODE_ENV=production node dist/index.js
    healthCheckPath: /healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: the-real-deal
          property: connectionString
    # the same thing based on the Dockerfile
  # - type: web
  #   region: frankfurt
  #   name: the-real-deal-docker
  #   env: docker
  #   healthCheckPath: /healthcheck
  #   envVars:
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: the-real-deal
  #         property: connectionString
databases:
  - name: the-real-deal
    databaseName: mydb
    region: frankfurt
