### See https://github.com/Huachao/vscode-restclient
### for some deeper insight
GET http://localhost:3000?foo=bah

###

GET http://localhost:3000/healthcheck

### Cats

GET http://localhost:3000/cats

### Cat by id

GET http://localhost:3000/cats/1

### moods of cat

GET http://localhost:3000/cats/1/moods

### POST Cats

POST http://localhost:3000/cats
Content-Type: application/json

{
  "name": "Mister Snugglesworth",
  "catchPhrase": "Meooww. Snuggle me"
}

### POST Mood to Cat by Id

POST http://localhost:3000/cats/1/moods
Content-Type: application/json

{
  "name": "grumpy"
}
